// <autogenerated />
namespace Wheel_32_Colors_32_Tracker
{
	partial class MainForm
	{
		/// <summary>
		/// Designer variable used to keep track of non-visual components.
		/// </summary>
		private System.ComponentModel.IContainer components = null;
		
		/// <summary>
		/// Disposes resources used by the form.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing) {
				if (components != null) {
					components.Dispose();
				}
			}
			base.Dispose(disposing);
		}
		
		/// <summary>
		/// This method is required for Windows Forms designer support.
		/// Do not change the method contents inside the source code editor. The Forms designer might
		/// not be able to load this method if it was changed manually.
		/// </summary>
		private void InitializeComponent()
		{
			System.Windows.Forms.DataVisualization.Charting.ChartArea chartArea1 = new System.Windows.Forms.DataVisualization.Charting.ChartArea();
			System.Windows.Forms.DataVisualization.Charting.Legend legend1 = new System.Windows.Forms.DataVisualization.Charting.Legend();
			System.Windows.Forms.DataVisualization.Charting.Series series1 = new System.Windows.Forms.DataVisualization.Charting.Series();
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint1 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint2 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint3 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint4 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint5 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint6 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint7 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint8 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint9 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint10 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint11 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint12 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint13 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint14 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint15 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint16 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint17 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint18 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint19 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint20 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint21 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint22 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint23 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint24 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint25 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint26 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint27 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint28 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint29 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint30 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint31 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint32 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint33 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint34 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint35 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint36 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			System.Windows.Forms.DataVisualization.Charting.DataPoint dataPoint37 = new System.Windows.Forms.DataVisualization.Charting.DataPoint(0D, 2.7027027027D);
			this.mainStatusStrip = new System.Windows.Forms.StatusStrip();
			this.historyToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
			this.historyCountToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
			this.xToolStripMenuItem8 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem7 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem6 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem5 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem9 = new System.Windows.Forms.ToolStripMenuItem();
			this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.mainColorDialog = new System.Windows.Forms.ColorDialog();
			this.resetButton = new System.Windows.Forms.Button();
			this.xToolStripMenuItem4 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem3 = new System.Windows.Forms.ToolStripMenuItem();
			this.editToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.resetToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.mainMenuStrip = new System.Windows.Forms.MenuStrip();
			this.optionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.setColorsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
			this.xToolStripMenuItem2 = new System.Windows.Forms.ToolStripMenuItem();
			this.wheelChart = new System.Windows.Forms.DataVisualization.Charting.Chart();
			this.mainStatusStrip.SuspendLayout();
			this.mainMenuStrip.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.wheelChart)).BeginInit();
			this.SuspendLayout();
			// 
			// mainStatusStrip
			// 
			this.mainStatusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.historyToolStripStatusLabel,
									this.historyCountToolStripStatusLabel});
			this.mainStatusStrip.Location = new System.Drawing.Point(0, 410);
			this.mainStatusStrip.Name = "mainStatusStrip";
			this.mainStatusStrip.Size = new System.Drawing.Size(438, 22);
			this.mainStatusStrip.TabIndex = 5;
			this.mainStatusStrip.Text = "statusStrip1";
			// 
			// historyToolStripStatusLabel
			// 
			this.historyToolStripStatusLabel.Name = "historyToolStripStatusLabel";
			this.historyToolStripStatusLabel.Size = new System.Drawing.Size(45, 17);
			this.historyToolStripStatusLabel.Text = "History:";
			// 
			// historyCountToolStripStatusLabel
			// 
			this.historyCountToolStripStatusLabel.Font = new System.Drawing.Font("Tahoma", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.historyCountToolStripStatusLabel.Name = "historyCountToolStripStatusLabel";
			this.historyCountToolStripStatusLabel.Size = new System.Drawing.Size(15, 17);
			this.historyCountToolStripStatusLabel.Text = "0";
			// 
			// xToolStripMenuItem8
			// 
			this.xToolStripMenuItem8.Name = "xToolStripMenuItem8";
			this.xToolStripMenuItem8.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D9)));
			this.xToolStripMenuItem8.Size = new System.Drawing.Size(152, 22);
			this.xToolStripMenuItem8.Text = "9x";
			// 
			// xToolStripMenuItem7
			// 
			this.xToolStripMenuItem7.Name = "xToolStripMenuItem7";
			this.xToolStripMenuItem7.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D8)));
			this.xToolStripMenuItem7.Size = new System.Drawing.Size(152, 22);
			this.xToolStripMenuItem7.Text = "&8x";
			// 
			// xToolStripMenuItem6
			// 
			this.xToolStripMenuItem6.Name = "xToolStripMenuItem6";
			this.xToolStripMenuItem6.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D7)));
			this.xToolStripMenuItem6.Size = new System.Drawing.Size(152, 22);
			this.xToolStripMenuItem6.Text = "&7x";
			// 
			// xToolStripMenuItem5
			// 
			this.xToolStripMenuItem5.Name = "xToolStripMenuItem5";
			this.xToolStripMenuItem5.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D6)));
			this.xToolStripMenuItem5.Size = new System.Drawing.Size(152, 22);
			this.xToolStripMenuItem5.Text = "&6x";
			// 
			// xToolStripMenuItem9
			// 
			this.xToolStripMenuItem9.Name = "xToolStripMenuItem9";
			this.xToolStripMenuItem9.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D0)));
			this.xToolStripMenuItem9.Size = new System.Drawing.Size(152, 22);
			this.xToolStripMenuItem9.Text = "1&0x";
			// 
			// helpToolStripMenuItem
			// 
			this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.aboutToolStripMenuItem});
			this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
			this.helpToolStripMenuItem.Size = new System.Drawing.Size(40, 20);
			this.helpToolStripMenuItem.Text = "&Help";
			// 
			// aboutToolStripMenuItem
			// 
			this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
			this.aboutToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.A)));
			this.aboutToolStripMenuItem.Size = new System.Drawing.Size(154, 22);
			this.aboutToolStripMenuItem.Text = "&About...";
			this.aboutToolStripMenuItem.Click += new System.EventHandler(this.OnAboutToolStripMenuItemClick);
			// 
			// resetButton
			// 
			this.resetButton.Anchor = System.Windows.Forms.AnchorStyles.None;
			this.resetButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.resetButton.ForeColor = System.Drawing.Color.Red;
			this.resetButton.Location = new System.Drawing.Point(129, 200);
			this.resetButton.Name = "resetButton";
			this.resetButton.Size = new System.Drawing.Size(180, 33);
			this.resetButton.TabIndex = 8;
			this.resetButton.Text = "&Reset";
			this.resetButton.UseVisualStyleBackColor = true;
			this.resetButton.Click += new System.EventHandler(this.OnResetButtonClick);
			// 
			// xToolStripMenuItem4
			// 
			this.xToolStripMenuItem4.Name = "xToolStripMenuItem4";
			this.xToolStripMenuItem4.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D5)));
			this.xToolStripMenuItem4.Size = new System.Drawing.Size(152, 22);
			this.xToolStripMenuItem4.Text = "5x";
			// 
			// xToolStripMenuItem3
			// 
			this.xToolStripMenuItem3.Name = "xToolStripMenuItem3";
			this.xToolStripMenuItem3.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D4)));
			this.xToolStripMenuItem3.Size = new System.Drawing.Size(152, 22);
			this.xToolStripMenuItem3.Text = "&4x";
			// 
			// editToolStripMenuItem
			// 
			this.editToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.resetToolStripMenuItem});
			this.editToolStripMenuItem.Name = "editToolStripMenuItem";
			this.editToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
			this.editToolStripMenuItem.Text = "&Edit";
			// 
			// resetToolStripMenuItem
			// 
			this.resetToolStripMenuItem.Name = "resetToolStripMenuItem";
			this.resetToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.R)));
			this.resetToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
			this.resetToolStripMenuItem.Text = "&Reset";
			this.resetToolStripMenuItem.Click += new System.EventHandler(this.OnResetButtonClick);
			// 
			// mainMenuStrip
			// 
			this.mainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.editToolStripMenuItem,
									this.optionsToolStripMenuItem,
									this.helpToolStripMenuItem});
			this.mainMenuStrip.Location = new System.Drawing.Point(0, 0);
			this.mainMenuStrip.Name = "mainMenuStrip";
			this.mainMenuStrip.Size = new System.Drawing.Size(438, 24);
			this.mainMenuStrip.TabIndex = 6;
			this.mainMenuStrip.Text = "menuStrip1";
			// 
			// optionsToolStripMenuItem
			// 
			this.optionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.setColorsToolStripMenuItem});
			this.optionsToolStripMenuItem.Name = "optionsToolStripMenuItem";
			this.optionsToolStripMenuItem.Size = new System.Drawing.Size(56, 20);
			this.optionsToolStripMenuItem.Text = "&Options";
			// 
			// setColorsToolStripMenuItem
			// 
			this.setColorsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
									this.xToolStripMenuItem,
									this.xToolStripMenuItem1,
									this.xToolStripMenuItem2,
									this.xToolStripMenuItem3,
									this.xToolStripMenuItem4,
									this.xToolStripMenuItem5,
									this.xToolStripMenuItem6,
									this.xToolStripMenuItem7,
									this.xToolStripMenuItem8,
									this.xToolStripMenuItem9});
			this.setColorsToolStripMenuItem.Name = "setColorsToolStripMenuItem";
			this.setColorsToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
			this.setColorsToolStripMenuItem.Text = "&Set colors";
			this.setColorsToolStripMenuItem.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.OnSetColorsToolStripMenuItemDropDownItemClicked);
			// 
			// xToolStripMenuItem
			// 
			this.xToolStripMenuItem.Name = "xToolStripMenuItem";
			this.xToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D1)));
			this.xToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
			this.xToolStripMenuItem.Text = "&1x";
			// 
			// xToolStripMenuItem1
			// 
			this.xToolStripMenuItem1.Name = "xToolStripMenuItem1";
			this.xToolStripMenuItem1.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D2)));
			this.xToolStripMenuItem1.Size = new System.Drawing.Size(152, 22);
			this.xToolStripMenuItem1.Text = "&2x";
			// 
			// xToolStripMenuItem2
			// 
			this.xToolStripMenuItem2.Name = "xToolStripMenuItem2";
			this.xToolStripMenuItem2.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D3)));
			this.xToolStripMenuItem2.Size = new System.Drawing.Size(152, 22);
			this.xToolStripMenuItem2.Text = "&3x";
			// 
			// wheelChart
			// 
			chartArea1.Name = "WheelChartArea";
			this.wheelChart.ChartAreas.Add(chartArea1);
			this.wheelChart.Dock = System.Windows.Forms.DockStyle.Fill;
			legend1.Name = "Legend1";
			this.wheelChart.Legends.Add(legend1);
			this.wheelChart.Location = new System.Drawing.Point(0, 24);
			this.wheelChart.Name = "wheelChart";
			series1.ChartArea = "WheelChartArea";
			series1.ChartType = System.Windows.Forms.DataVisualization.Charting.SeriesChartType.Doughnut;
			series1.CustomProperties = "PieDrawingStyle=SoftEdge, PieStartAngle=265, DoughnutRadius=20";
			series1.IsVisibleInLegend = false;
			series1.Legend = "Legend1";
			series1.Name = "WheelChartSeries";
			dataPoint1.BorderColor = System.Drawing.Color.Black;
			dataPoint1.BorderWidth = 2;
			dataPoint1.Color = System.Drawing.Color.Green;
			dataPoint1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint1.IsValueShownAsLabel = false;
			dataPoint1.Label = "0";
			dataPoint1.LabelForeColor = System.Drawing.Color.White;
			dataPoint2.BorderColor = System.Drawing.Color.Black;
			dataPoint2.BorderWidth = 2;
			dataPoint2.Color = System.Drawing.Color.Red;
			dataPoint2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint2.Label = "32";
			dataPoint2.LabelForeColor = System.Drawing.Color.White;
			dataPoint3.BorderColor = System.Drawing.Color.Black;
			dataPoint3.BorderWidth = 2;
			dataPoint3.Color = System.Drawing.Color.Black;
			dataPoint3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint3.Label = "15";
			dataPoint3.LabelForeColor = System.Drawing.Color.White;
			dataPoint4.BorderColor = System.Drawing.Color.Black;
			dataPoint4.BorderWidth = 2;
			dataPoint4.Color = System.Drawing.Color.Red;
			dataPoint4.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint4.Label = "19";
			dataPoint4.LabelForeColor = System.Drawing.Color.White;
			dataPoint5.BorderColor = System.Drawing.Color.Black;
			dataPoint5.BorderWidth = 2;
			dataPoint5.Color = System.Drawing.Color.Black;
			dataPoint5.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint5.Label = "4";
			dataPoint5.LabelForeColor = System.Drawing.Color.White;
			dataPoint6.BorderColor = System.Drawing.Color.Black;
			dataPoint6.BorderWidth = 2;
			dataPoint6.Color = System.Drawing.Color.Red;
			dataPoint6.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint6.Label = "21";
			dataPoint6.LabelForeColor = System.Drawing.Color.White;
			dataPoint7.BorderColor = System.Drawing.Color.Black;
			dataPoint7.BorderWidth = 2;
			dataPoint7.Color = System.Drawing.Color.Black;
			dataPoint7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint7.Label = "2";
			dataPoint7.LabelForeColor = System.Drawing.Color.White;
			dataPoint8.BorderColor = System.Drawing.Color.Black;
			dataPoint8.BorderWidth = 2;
			dataPoint8.Color = System.Drawing.Color.Red;
			dataPoint8.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint8.Label = "25";
			dataPoint8.LabelForeColor = System.Drawing.Color.White;
			dataPoint9.BorderColor = System.Drawing.Color.Black;
			dataPoint9.BorderWidth = 2;
			dataPoint9.Color = System.Drawing.Color.Black;
			dataPoint9.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint9.Label = "17";
			dataPoint9.LabelForeColor = System.Drawing.Color.White;
			dataPoint10.BorderColor = System.Drawing.Color.Black;
			dataPoint10.BorderWidth = 2;
			dataPoint10.Color = System.Drawing.Color.Red;
			dataPoint10.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint10.Label = "34";
			dataPoint10.LabelForeColor = System.Drawing.Color.White;
			dataPoint11.BorderColor = System.Drawing.Color.Black;
			dataPoint11.BorderWidth = 2;
			dataPoint11.Color = System.Drawing.Color.Black;
			dataPoint11.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint11.Label = "6";
			dataPoint11.LabelForeColor = System.Drawing.Color.White;
			dataPoint12.BorderColor = System.Drawing.Color.Black;
			dataPoint12.BorderWidth = 2;
			dataPoint12.Color = System.Drawing.Color.Red;
			dataPoint12.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint12.Label = "27";
			dataPoint12.LabelForeColor = System.Drawing.Color.White;
			dataPoint13.BorderColor = System.Drawing.Color.Black;
			dataPoint13.BorderWidth = 2;
			dataPoint13.Color = System.Drawing.Color.Black;
			dataPoint13.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint13.Label = "13";
			dataPoint13.LabelForeColor = System.Drawing.Color.White;
			dataPoint14.BorderColor = System.Drawing.Color.Black;
			dataPoint14.BorderWidth = 2;
			dataPoint14.Color = System.Drawing.Color.Red;
			dataPoint14.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint14.Label = "36";
			dataPoint14.LabelForeColor = System.Drawing.Color.White;
			dataPoint15.BorderColor = System.Drawing.Color.Black;
			dataPoint15.BorderWidth = 2;
			dataPoint15.Color = System.Drawing.Color.Black;
			dataPoint15.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint15.Label = "11";
			dataPoint15.LabelForeColor = System.Drawing.Color.White;
			dataPoint16.BorderColor = System.Drawing.Color.Black;
			dataPoint16.BorderWidth = 2;
			dataPoint16.Color = System.Drawing.Color.Red;
			dataPoint16.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint16.Label = "30";
			dataPoint16.LabelForeColor = System.Drawing.Color.White;
			dataPoint17.BorderColor = System.Drawing.Color.Black;
			dataPoint17.BorderWidth = 2;
			dataPoint17.Color = System.Drawing.Color.Black;
			dataPoint17.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint17.Label = "8";
			dataPoint17.LabelForeColor = System.Drawing.Color.White;
			dataPoint18.BorderColor = System.Drawing.Color.Black;
			dataPoint18.BorderWidth = 2;
			dataPoint18.Color = System.Drawing.Color.Red;
			dataPoint18.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint18.Label = "23";
			dataPoint18.LabelForeColor = System.Drawing.Color.White;
			dataPoint19.BorderColor = System.Drawing.Color.Black;
			dataPoint19.BorderWidth = 2;
			dataPoint19.Color = System.Drawing.Color.Black;
			dataPoint19.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint19.Label = "10";
			dataPoint19.LabelForeColor = System.Drawing.Color.White;
			dataPoint20.BorderColor = System.Drawing.Color.Black;
			dataPoint20.BorderWidth = 2;
			dataPoint20.Color = System.Drawing.Color.Red;
			dataPoint20.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint20.Label = "5";
			dataPoint20.LabelForeColor = System.Drawing.Color.White;
			dataPoint21.BorderColor = System.Drawing.Color.Black;
			dataPoint21.BorderWidth = 2;
			dataPoint21.Color = System.Drawing.Color.Black;
			dataPoint21.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint21.Label = "24";
			dataPoint21.LabelForeColor = System.Drawing.Color.White;
			dataPoint22.BorderColor = System.Drawing.Color.Black;
			dataPoint22.BorderWidth = 2;
			dataPoint22.Color = System.Drawing.Color.Red;
			dataPoint22.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint22.Label = "16";
			dataPoint22.LabelForeColor = System.Drawing.Color.White;
			dataPoint23.BorderColor = System.Drawing.Color.Black;
			dataPoint23.BorderWidth = 2;
			dataPoint23.Color = System.Drawing.Color.Black;
			dataPoint23.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint23.Label = "33";
			dataPoint23.LabelForeColor = System.Drawing.Color.White;
			dataPoint24.BorderColor = System.Drawing.Color.Black;
			dataPoint24.BorderWidth = 2;
			dataPoint24.Color = System.Drawing.Color.Red;
			dataPoint24.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint24.Label = "1";
			dataPoint24.LabelForeColor = System.Drawing.Color.White;
			dataPoint25.BorderColor = System.Drawing.Color.Black;
			dataPoint25.BorderWidth = 2;
			dataPoint25.Color = System.Drawing.Color.Black;
			dataPoint25.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint25.Label = "20";
			dataPoint25.LabelForeColor = System.Drawing.Color.White;
			dataPoint26.BorderColor = System.Drawing.Color.Black;
			dataPoint26.BorderWidth = 2;
			dataPoint26.Color = System.Drawing.Color.Red;
			dataPoint26.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint26.Label = "14";
			dataPoint26.LabelForeColor = System.Drawing.Color.White;
			dataPoint27.BorderColor = System.Drawing.Color.Black;
			dataPoint27.BorderWidth = 2;
			dataPoint27.Color = System.Drawing.Color.Black;
			dataPoint27.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint27.Label = "31";
			dataPoint27.LabelForeColor = System.Drawing.Color.White;
			dataPoint28.BorderColor = System.Drawing.Color.Black;
			dataPoint28.BorderWidth = 2;
			dataPoint28.Color = System.Drawing.Color.Red;
			dataPoint28.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint28.Label = "9";
			dataPoint28.LabelForeColor = System.Drawing.Color.White;
			dataPoint29.BorderColor = System.Drawing.Color.Black;
			dataPoint29.BorderWidth = 2;
			dataPoint29.Color = System.Drawing.Color.Black;
			dataPoint29.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint29.Label = "22";
			dataPoint29.LabelForeColor = System.Drawing.Color.White;
			dataPoint30.BorderColor = System.Drawing.Color.Black;
			dataPoint30.BorderWidth = 2;
			dataPoint30.Color = System.Drawing.Color.Red;
			dataPoint30.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint30.Label = "18";
			dataPoint30.LabelForeColor = System.Drawing.Color.White;
			dataPoint31.BorderColor = System.Drawing.Color.Black;
			dataPoint31.BorderWidth = 2;
			dataPoint31.Color = System.Drawing.Color.Black;
			dataPoint31.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint31.Label = "29";
			dataPoint31.LabelForeColor = System.Drawing.Color.White;
			dataPoint32.BorderColor = System.Drawing.Color.Black;
			dataPoint32.BorderWidth = 2;
			dataPoint32.Color = System.Drawing.Color.Red;
			dataPoint32.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint32.Label = "7";
			dataPoint32.LabelForeColor = System.Drawing.Color.White;
			dataPoint33.BorderColor = System.Drawing.Color.Black;
			dataPoint33.BorderWidth = 2;
			dataPoint33.Color = System.Drawing.Color.Black;
			dataPoint33.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint33.Label = "28";
			dataPoint33.LabelForeColor = System.Drawing.Color.White;
			dataPoint34.BorderColor = System.Drawing.Color.Black;
			dataPoint34.BorderWidth = 2;
			dataPoint34.Color = System.Drawing.Color.Red;
			dataPoint34.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint34.Label = "12";
			dataPoint34.LabelForeColor = System.Drawing.Color.White;
			dataPoint35.BorderColor = System.Drawing.Color.Black;
			dataPoint35.BorderWidth = 2;
			dataPoint35.Color = System.Drawing.Color.Black;
			dataPoint35.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint35.Label = "35";
			dataPoint35.LabelForeColor = System.Drawing.Color.White;
			dataPoint36.BorderColor = System.Drawing.Color.Black;
			dataPoint36.BorderWidth = 2;
			dataPoint36.Color = System.Drawing.Color.Red;
			dataPoint36.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint36.Label = "3";
			dataPoint36.LabelForeColor = System.Drawing.Color.White;
			dataPoint37.BorderColor = System.Drawing.Color.Black;
			dataPoint37.BorderWidth = 2;
			dataPoint37.Color = System.Drawing.Color.Black;
			dataPoint37.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			dataPoint37.Label = "26";
			dataPoint37.LabelForeColor = System.Drawing.Color.White;
			series1.Points.Add(dataPoint1);
			series1.Points.Add(dataPoint2);
			series1.Points.Add(dataPoint3);
			series1.Points.Add(dataPoint4);
			series1.Points.Add(dataPoint5);
			series1.Points.Add(dataPoint6);
			series1.Points.Add(dataPoint7);
			series1.Points.Add(dataPoint8);
			series1.Points.Add(dataPoint9);
			series1.Points.Add(dataPoint10);
			series1.Points.Add(dataPoint11);
			series1.Points.Add(dataPoint12);
			series1.Points.Add(dataPoint13);
			series1.Points.Add(dataPoint14);
			series1.Points.Add(dataPoint15);
			series1.Points.Add(dataPoint16);
			series1.Points.Add(dataPoint17);
			series1.Points.Add(dataPoint18);
			series1.Points.Add(dataPoint19);
			series1.Points.Add(dataPoint20);
			series1.Points.Add(dataPoint21);
			series1.Points.Add(dataPoint22);
			series1.Points.Add(dataPoint23);
			series1.Points.Add(dataPoint24);
			series1.Points.Add(dataPoint25);
			series1.Points.Add(dataPoint26);
			series1.Points.Add(dataPoint27);
			series1.Points.Add(dataPoint28);
			series1.Points.Add(dataPoint29);
			series1.Points.Add(dataPoint30);
			series1.Points.Add(dataPoint31);
			series1.Points.Add(dataPoint32);
			series1.Points.Add(dataPoint33);
			series1.Points.Add(dataPoint34);
			series1.Points.Add(dataPoint35);
			series1.Points.Add(dataPoint36);
			series1.Points.Add(dataPoint37);
			this.wheelChart.Series.Add(series1);
			this.wheelChart.Size = new System.Drawing.Size(438, 386);
			this.wheelChart.TabIndex = 9;
			// 
			// MainForm
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(438, 432);
			this.Controls.Add(this.resetButton);
			this.Controls.Add(this.wheelChart);
			this.Controls.Add(this.mainStatusStrip);
			this.Controls.Add(this.mainMenuStrip);
			this.MinimumSize = new System.Drawing.Size(346, 366);
			this.Name = "MainForm";
			this.Text = "Wheel Colors Tracker";
			this.mainStatusStrip.ResumeLayout(false);
			this.mainStatusStrip.PerformLayout();
			this.mainMenuStrip.ResumeLayout(false);
			this.mainMenuStrip.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.wheelChart)).EndInit();
			this.ResumeLayout(false);
			this.PerformLayout();
		}
		private System.Windows.Forms.DataVisualization.Charting.Chart wheelChart;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem2;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem1;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem setColorsToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem optionsToolStripMenuItem;
		private System.Windows.Forms.MenuStrip mainMenuStrip;
		private System.Windows.Forms.ToolStripMenuItem resetToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem editToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem3;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem4;
		private System.Windows.Forms.Button resetButton;
		private System.Windows.Forms.ColorDialog mainColorDialog;
		private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem9;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem5;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem6;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem7;
		private System.Windows.Forms.ToolStripMenuItem xToolStripMenuItem8;
		private System.Windows.Forms.ToolStripStatusLabel historyCountToolStripStatusLabel;
		private System.Windows.Forms.ToolStripStatusLabel historyToolStripStatusLabel;
		private System.Windows.Forms.StatusStrip mainStatusStrip;
	}
}
